openapi: 3.0.3
info:
    title: TODO API
    version: 1.0.0
    description: >
        API de gestion d'une TODO List.
servers:
    -   url: http://localhost:8080
        description: Serveur local de développement

tags:
    -   name: tasks
        description: Opérations sur les tâches

paths:
    /tasks:
        post:
            tags: [ tasks ]
            summary: Créer une tâche
            operationId: createTask
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Task'
            responses:
                '201':
                    description: Tâche créée avec succès
                    headers:
                        Location:
                            description: URL de la ressource créée
                            schema:
                                type: string
                                example: /tasks/1
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Task'
        get:
            tags: [ tasks ]
            summary: Récupérer toutes les tâches
            description: Récupérer toutes les tâches ou seulement celles qui sont à faire
            operationId: getAllTask
            parameters:
                -   in: query
                    name: todo
                    required: false
                    description: indique si il faut toutes les tâche ou seulement celles qui reste à faire
                    schema:
                        type: boolean
            responses:
                '200':
                    description: Tâches trouvées avec succès
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Task'
                '404':
                    description: Tâches non trouvées

    /tasks/{id}:
        parameters:
            -   in: path
                name: id
                required: true
                description: Identifiant numérique de la tâche
                schema:
                    type: integer
                    minimum: 1
        get:
            tags: [ tasks ]
            summary: Récupérer une tâche
            description: Récupérer une tâche par son identifiant
            operationId: getTaskById
            responses:
                '200':
                    description: Tâche trouvée avec succès
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Task'
                '404':
                    description: Tâche non trouvée
            
        put:
            tags: [ tasks ]
            summary: modifier une tâche
            description: modifier la tache id
            operationId: putTaskById
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Task'
            responses:
                '200':
                    description: Tâches modifiée avec succès
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Task'
                '404':
                    description: Tâches non trouvées

        delete:
            tags: [ tasks ]
            summary: supprimer une tâche
            description: supprimer la tache par son identifiant
            operationId: delTaskById
            responses:
                '200':
                    description: Tâches supprimer avec succès
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Task'
                '404':
                    description: Tâches non supprimer


components:
    schemas:
        Task:
            type: object
            description: Représentation d'une tâche
            properties:
                id:
                    type: integer
                    example: 1
                title:
                    type: string
                    nullable: false
                    example: Acheter du lait
                description:
                    type: string
                    nullable: true
                    example: 2L demi-écrémé
                done:
                    type: boolean
                    nullable: false
                    example: false
            required:
                - id
                - title


